### ISSUE TITLE
Add ENABLE_SSE=OFF flag will compile unsuccessfully

### ISSUE THREAD

**Issue by uddmorningsun** [conda-forge/libhdfs3-feedstock#28]
Hi, maybe my issues reported incorrectly for this, apologize in advance for my behavior. I don't see https://github.com/ContinuumIO/libhdfs3-downstream any update, so issue it.

I known I should use `pyarrow` according to `README.md`, since project requirements I'm working on compiling it in `mips64` arch to package it. When I'm ready to test with `hdfs3` python library, it raises undefined symbol error:

```
[root@lx-app-1 yancy]# LD_LIBRARY_PATH=/usr/local/libhdfs3-2.2.31/lib/ /tmp/test-venv/bin/python
Python 3.7.5 (default, Oct 22 2019, 22:44:31)
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hdfs3.lib import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test-venv/lib/python3.7/site-packages/hdfs3/lib.py", line 17, in <module>
    _lib = ct.cdll.LoadLibrary(name)
  File "/opt/python3/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/opt/python3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/libhdfs3-2.2.31/lib/libhdfs3.so: undefined symbol: _ZTVN4Hdfs8Internal8HWCrc32cE
```
I have debug and then find a possible reason finally, since my machine doesn't support SSE:
```
[ 21%] Building CXX object src/CMakeFiles/libhdfs3-shared.dir/client/EncryptionZoneIterator.cpp.o
cd /tmp/libhdfs3-downstream/libhdfs3/build/src && /usr/lib64/ccache/c++  -DTEST_HDFS_PREFIX=\"./\" -D_GNU_SOURCE -D__STDC_FORMAT_MACROS -Dlibhdfs3_shared_EXPORTS -I/tmp/libhdfs3-downstream/libhdfs3/src -I/tmp/libhdfs3-downstream/libhdfs3/src/common -I/tmp/libhdfs3-downstream/libhdfs3/build/src -I/usr/include/libxml2 -I/tmp/libhdfs3-downstream/libhdfs3/mock  -fno-strict-aliasing
 -fno-omit-frame-pointer -msse4.2 -Wl,--export-dynamic -std=c++0x -D_GLIBCXX_USE_NANOSLEEP -Wall -O2 -DNDEBUG -fPIC   -o CMakeFiles/libhdfs3-shared.dir/client/EncryptionZoneIterator.cpp.o -c
 /tmp/libhdfs3-downstream/libhdfs3/src/client/EncryptionZoneIterator.cpp
c++: error: unrecognized command line option '-msse4.2'
src/CMakeFiles/libhdfs3-shared.dir/build.make:281: recipe for target 'src/CMakeFiles/libhdfs3-shared.dir/client/FileSystemImpl.cpp.o' failed
make[2]: *** [src/CMakeFiles/libhdfs3-shared.dir/client/FileSystemImpl.cpp.o] Error 1
c++: error: unrecognized command line option '-msse4.2'
src/CMakeFiles/libhdfs3-shared.dir/build.make:185: recipe for target 'src/CMakeFiles/libhdfs3-shared.dir/client/DataTransferProtocolSender.cpp.o' failed
make[2]: *** [src/CMakeFiles/libhdfs3-shared.dir/client/DataTransferProtocolSender.cpp.o] Error 1
c++: error: unrecognized command line option '-msse4.2'
c++: error: unrecognized command line option '-msse4.2'
```
So, I need add `-DENABLE_SSE=OFF` flag to compile again, it finished. But build is successful, `from hdfs3.lib import *` will raise error. And then, I find if `x86_64` machine add `-DENABLE_SSE=OFF` flag, compile progress will fail finally.
* `cmake -DENABLE_DEBUG=OFF -DENABLE_SSE=OFF -DCMAKE_INSTALL_PREFIX=/usr/local/libhdfs3-2.2.31  -DENABLE_BOOST=OFF -DENABLE_COVERAGE=OFF -DENABLE_LIBCPP=OFF  ..`: fail
```
[ 65%] Building CXX object src/CMakeFiles/libhdfs3-static.dir/network/BufferedSocketReader.cpp.o
cd /root/libhdfs3-downstream/libhdfs3/build/src && /opt/rh/devtoolset-8/root/bin/c++   -DTEST_HDFS_PREFIX=\"./\" -D_GNU_SOURCE -D__STDC_FORMAT_MACROS -fno-strict-aliasing -f
no-omit-frame-pointer -Wl,--export-dynamic -std=c++0x -D_GLIBCXX_USE_NANOSLEEP -Wall -O2 -g -DNDEBUG -I/root/libhdfs3-downstream/libhdfs3/src -I/root/libhdfs3-downstream/lib
hdfs3/src/common -I/root/libhdfs3-downstream/libhdfs3/build/src -I/usr/include/libxml2 -I/root/libhdfs3-downstream/libhdfs3/mock    -fdiagnostics-color=always -o CMakeFiles/
libhdfs3-static.dir/network/BufferedSocketReader.cpp.o -c /root/libhdfs3-downstream/libhdfs3/src/network/BufferedSocketReader.cpp
/root/libhdfs3-downstream/libhdfs3/src/common/HWCrc32c.cpp: Assembler messages:
/root/libhdfs3-downstream/libhdfs3/src/common/HWCrc32c.cpp:50: Error: invalid instruction suffix for `crc32'
/usr/bin/cmake -E cmake_progress_report /root/libhdfs3-downstream/libhdfs3/build/CMakeFiles 83
/root/libhdfs3-downstream/libhdfs3/src/common/HWCrc32c.cpp:50: Error: invalid instruction suffix for `crc32'
make[2]: *** [src/CMakeFiles/libhdfs3-static.dir/build.make:1068: src/CMakeFiles/libhdfs3-static.dir/common/HWCrc32c.cpp.o] Error 1
```
* `cmake -DENABLE_DEBUG=OFF  -DCMAKE_INSTALL_PREFIX=/usr/local/libhdfs3-2.2.31  -DENABLE_BOOST=OFF -DENABLE_COVERAGE=OFF -DENABLE_LIBCPP=OFF  ..`: OK, and `from hdfs3.lib import *` is also OK

I have tried different version gcc, same result will produce. So, any plan to fix it in upstream for maintainer, thanks!

**Comment by martindurant** [comment]
This project is now retired, although some people still use it for legacy. You may be better off migrating to pyarrow (for hdfs via JN) or fsspec (webhdfs). However, you are welcome to still push PRs if you like, but I don't know how much of a review they would be able to get.

**Comment by uddmorningsun** [comment]
@martindurant Thanks your reply for this issue. To be honest, I'm not familiar with C++ fully, so I post issues to ask for help.

About `x86_64` machine add `ENABLE_DEBUG=OFF` can not compile successfully, do you or others maintainer have plan to fix it? If so, how about `mips64` ?

If there is no plan to fix it, I will close it ! Looking forward to your reply and good news sincerely

**Comment by martindurant** [comment]
There is plan from me, and I suspect neither from anyone else, sorry.
